codemagic updated

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -11,24 +11,19 @@ workflows:
       vars:
         PACKAGE_NAME: "io.codemagic.androidquicksample"
     scripts:
-    
-    - name: Build Android release
-      script: | 
-        ./gradlew bundleRelease # -> to create the .aab
-        # gradlew assembleRelease # -> to create the .apk
-    #   - name: Set Android SDK location
-    #     script: |
-    #       echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
-    #   - name: Build Android release
-    #     script: |
-    #       LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-    #       if [ -z LATEST_BUILD_NUMBER ]; then
-    #           # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
-    #           UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-    #       else
-    #           UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-    #       fi
-    #       ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
+      - name: Set Android SDK location
+        script: | 
+          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
+      - name: Build Android release
+        script: | 
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
     artifacts:
       - app/build/outputs/**/*.apk  # APK dosyalarını da ekleyin
       - app/build/outputs/**/*.aab
